server:
  port: 8080

spring:
  main:
    web-application-type: servlet

push:
  channels:
    - websocket
    - sms

external-user:
  base-url:
  user-path: /api/v1/users/{id}
  auth-header: Authorization
  auth-token:
  timeout: 2s

security:
  api-key:
